### PR TITLE
Update Dangerfile to use the organization one

### PR DESCRIPTION
**Pull request by pepibumur**

### CODE REVIEW

**Comment by yonaskolb** [comment]
Is the comment above supposed to look like that?

**Comment by pepibumur** [comment]
Nop @yonaskolb. There was an issue with the Danger file. I'm re-running the job.

**Comment by orta** [comment]
You could consider using [Danger Swift](https://github.com/danger/danger-swift) for a Dangerfile that simple? [Reference PR](https://github.com/Moya/Harvey/pull/13/files) ( use `npm install danger` not `npm install danger@alpha` though )

**Comment by pepibumur** [comment]
Nice! I'll do that instead. Thanks @orta

**Comment by pepibumur** [comment]
@orta just wondering. Can I use the `Danger.swift` definition reusing a `Dangerfile` define in another organization repository?

**Comment by orta** [comment]
Nope, that'd require some interesting work, because you'd need to compile and evaluate those Swift files, which is tricky enough for just the original `Dangerfile.swift`. It can definitely be built into danger-swift though the DSL though.

**Pull request merged**
