### PR TITLE
Fix search/replace issue in README

### PR DESCRIPTION
**Pull request by Mazyod**
**Issue:** None

### Short description
We all love xcproj's shiny new name, but perhaps we shouldn't update swift subcommand so it actually runs.

### Solution
Revert to the correct subcommand.

### Implementation

- [x] Cloned, tried to contribute, failed.
- [x] After some research, found the issue, fixed the command with SublimeText (Latest version!)

### CODE REVIEW

**Comment by pepibumur** [comment]
Good catch @Mazyod. Merging :)

**Comment by pepibumur** [comment]
I've added you as contributors @Mazyod so that you can write to the repository. Moreover, I'd like to invite you to the organization Slack http://xcodeswift.herokuapp.com/ where other members are 😛

**Comment by Mazyod** [comment]
Thanks! Btw, somehow the git repo url changed to a seemingly old org name

**Comment by pepibumur** [comment]
Solved @Mazyod 😛

**Pull request merged**
