### PR TITLE
Use (null) in comment when PBXBuildFile.name == nil

### PR DESCRIPTION
**Pull request by briantkelley**
### Short description 📝
When a `PBXBuildFile` is missing the name property, xcproj doesn't emit a comment for the encoding of the object or references to it. Xcode emites the string `"(null)"`.

### Solution 📦
Update the comment generation of `PBXBuildFile` and comment generation in `PBXBuildPhase` to use the string `"(null)"` when the `PBXProj.Objects.fileName(buildFileReference:)` return `nil`.

---
This change is [Reviewable](https://reviewable.io/reviews/xcodeswift/xcproj/203)

### CODE REVIEW

**Comment by yonaskolb** [comment]
That's pretty funny. Does Xcode actually go so far as to rewrite a missing comment as `(null)` when a project is opened?

**Comment by keith** [comment]
It does 🙃

**Comment by yonaskolb** [comment]
Ok cool 🤷‍♂️ 

Feel free to merge. The downside of making people add their own changelogs is the merge conflicts...

**Comment by yonaskolb** [comment]
To bad Shakira, Github's conflict resolver UI only does merge, not rebase. Squashing when merging this though 😉

**Comment by pepibumur** [comment]
Seriously? :trollface:, let's write "(null)" then. mmm interesting point about the CHANGELOG.md conflicts. Can't think of any way to solve that issue :/.

**Comment by yonaskolb** [comment]
Another way to manager the changelog is to have a release task write the list of merged PR's since the last version to the changelog automatically using the title, url and author 👍

**Comment by pepibumur** [comment]
Yeah, I thought about that one @yonaskolb but then people would need to tag somehow the PRs to know the kind of change that they are introducing and use proper titles that very descriptive. I'll check how other open-source projects are doing it.

**Pull request merged**
